addSbtPlugin("com.earldouglas"   % "xsbt-web-plugin"              % "4.2.4")
addSbtPlugin("com.github.atais"  % "sbt-eclipselink-static-weave" % "0.1.2")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"                  % "0.5.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"                      % "1.0.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"                   % "5.6.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"                 % "2.4.4")
addSbtPlugin("org.xerial.sbt"    % "sbt-pack"                     % "0.14")
addSbtPlugin("com.codecommit"    % "sbt-github-packages"          % "0.5.3")
