CREATE TABLE video_sequences (uuid VARCHAR(36) NOT NULL, camera_id VARCHAR(256) NOT NULL, description VARCHAR(2048), last_updated_time TIMESTAMP, name VARCHAR(512) NOT NULL UNIQUE, PRIMARY KEY (uuid))
CREATE INDEX idx_video_sequences__name ON video_sequences (name)
CREATE INDEX idx_video_sequences__camera_id ON video_sequences (camera_id)
CREATE TABLE videos (uuid VARCHAR(36) NOT NULL, description VARCHAR(2048), duration_millis BIGINT, last_updated_time TIMESTAMP, name VARCHAR(512) NOT NULL UNIQUE, start_time TIMESTAMP NOT NULL, video_sequence_uuid VARCHAR(36) NOT NULL, PRIMARY KEY (uuid))
CREATE INDEX idx_videos__name ON videos (name)
CREATE INDEX idx_videos__start_time ON videos (start_time)
CREATE INDEX idx_videos__video_sequence_uuid ON videos (video_sequence_uuid)
CREATE TABLE video_references (uuid VARCHAR(36) NOT NULL, audio_codec VARCHAR(128), container VARCHAR(128), description VARCHAR(2048), frame_rate FLOAT, height INTEGER, last_updated_time TIMESTAMP, sha512 VARCHAR(128), size_bytes BIGINT, uri VARCHAR(1024) NOT NULL UNIQUE, video_codec VARCHAR(128), width INTEGER, video_uuid VARCHAR(36) NOT NULL, PRIMARY KEY (uuid))
CREATE INDEX idx_video_references__uri ON video_references (uri)
CREATE INDEX idx_video_references__video_uuid ON video_references (video_uuid)
ALTER TABLE videos ADD CONSTRAINT vdsvdosequenceuuid FOREIGN KEY (video_sequence_uuid) REFERENCES video_sequences (uuid)
ALTER TABLE video_references ADD CONSTRAINT vdreferencesvduuid FOREIGN KEY (video_uuid) REFERENCES videos (uuid)
